import { PlatformConfig } from './types';

export const platformConfigs: Record<string, PlatformConfig> = {
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: '💬',
    colors: {
      sentBubble: '#005C4B',
      receivedBubble: '#202C33',
      sentText: '#E9EDEF',
      receivedText: '#E9EDEF',
      background: '#0B141A',
      header: '#1F2C34',
      headerText: '#E9EDEF',
      inputBar: '#1F2C34',
      accent: '#00A884',
      timestamp: '#FFFFFF99',
      statusBar: '#1F2C34',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: true,
      voiceNotes: true,
      onlineStatus: true,
      lastSeen: true,
      editMessage: true,
      deleteMessage: true,
    },
    fonts: {
      primary: "'Segoe UI', Helvetica, Arial, sans-serif",
      message: "'Segoe UI', Helvetica, Arial, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '7.5px',
      sentRadius: '7.5px 7.5px 0 7.5px',
      receivedRadius: '7.5px 7.5px 7.5px 0',
      maxWidth: '80%',
      padding: '6px 7px 8px 9px',
      hasTail: true,
    },
  },
  imessage: {
    id: 'imessage',
    name: 'iMessage',
    icon: '🍎',
    colors: {
      sentBubble: '#007AFF',
      receivedBubble: '#3A3A3C',
      sentText: '#FFFFFF',
      receivedText: '#FFFFFF',
      background: '#000000',
      header: '#1C1C1E',
      headerText: '#FFFFFF',
      inputBar: '#1C1C1E',
      accent: '#007AFF',
      timestamp: '#8E8E93',
      statusBar: '#000000',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: false,
      voiceNotes: true,
      onlineStatus: false,
      lastSeen: false,
      editMessage: true,
      deleteMessage: true,
    },
    fonts: {
      primary: "-apple-system, 'SF Pro Display', BlinkMacSystemFont, sans-serif",
      message: "-apple-system, 'SF Pro Text', BlinkMacSystemFont, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '18px',
      sentRadius: '18px 18px 4px 18px',
      receivedRadius: '18px 18px 18px 4px',
      maxWidth: '75%',
      padding: '8px 12px',
      hasTail: true,
    },
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram DM',
    icon: '📸',
    colors: {
      sentBubble: '#3797F0',
      receivedBubble: '#262626',
      sentText: '#FFFFFF',
      receivedText: '#F5F5F5',
      background: '#000000',
      header: '#000000',
      headerText: '#F5F5F5',
      inputBar: '#000000',
      accent: '#E1306C',
      timestamp: '#A8A8A8',
      statusBar: '#000000',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: true,
      voiceNotes: true,
      onlineStatus: true,
      lastSeen: false,
      editMessage: false,
      deleteMessage: true,
    },
    fonts: {
      primary: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      message: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '22px',
      sentRadius: '22px 22px 4px 22px',
      receivedRadius: '22px 22px 22px 4px',
      maxWidth: '75%',
      padding: '10px 14px',
      hasTail: false,
    },
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    icon: '✈️',
    colors: {
      sentBubble: '#2B5278',
      receivedBubble: '#182533',
      sentText: '#FFFFFF',
      receivedText: '#FFFFFF',
      background: '#0E1621',
      header: '#17212B',
      headerText: '#FFFFFF',
      inputBar: '#17212B',
      accent: '#5EAAEE',
      timestamp: '#6D7883',
      statusBar: '#17212B',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: true,
      voiceNotes: true,
      onlineStatus: true,
      lastSeen: true,
      editMessage: true,
      deleteMessage: true,
    },
    fonts: {
      primary: "Roboto, 'Segoe UI', sans-serif",
      message: "Roboto, 'Segoe UI', sans-serif",
    },
    bubbleStyle: {
      borderRadius: '12px',
      sentRadius: '12px 12px 0 12px',
      receivedRadius: '12px 12px 12px 0',
      maxWidth: '80%',
      padding: '7px 10px 8px',
      hasTail: true,
    },
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    icon: '🎮',
    colors: {
      sentBubble: '#2B2D31',
      receivedBubble: '#2B2D31',
      sentText: '#DBDEE1',
      receivedText: '#DBDEE1',
      background: '#313338',
      header: '#1E1F22',
      headerText: '#F2F3F5',
      inputBar: '#383A40',
      accent: '#5865F2',
      timestamp: '#949BA4',
      statusBar: '#1E1F22',
    },
    features: {
      readReceipts: false,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: false,
      voiceNotes: false,
      onlineStatus: true,
      lastSeen: false,
      editMessage: true,
      deleteMessage: true,
    },
    fonts: {
      primary: "'gg sans', 'Noto Sans', 'Helvetica Neue', Helvetica, sans-serif",
      message: "'gg sans', 'Noto Sans', 'Helvetica Neue', Helvetica, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '4px',
      sentRadius: '4px',
      receivedRadius: '4px',
      maxWidth: '100%',
      padding: '2px 0',
      hasTail: false,
    },
  },
  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    icon: '👻',
    colors: {
      sentBubble: '#0FADFF',
      receivedBubble: '#1C1C1E',
      sentText: '#FFFFFF',
      receivedText: '#FFFFFF',
      background: '#000000',
      header: '#1C1C1E',
      headerText: '#FFFFFF',
      inputBar: '#1C1C1E',
      accent: '#FFFC00',
      timestamp: '#8E8E93',
      statusBar: '#000000',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: false,
      voiceNotes: true,
      onlineStatus: false,
      lastSeen: false,
      editMessage: false,
      deleteMessage: true,
    },
    fonts: {
      primary: "'Avenir Next', 'Avenir', Helvetica, sans-serif",
      message: "'Avenir Next', 'Avenir', Helvetica, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '20px',
      sentRadius: '20px 20px 4px 20px',
      receivedRadius: '20px 20px 20px 4px',
      maxWidth: '75%',
      padding: '10px 14px',
      hasTail: false,
    },
  },
  messenger: {
    id: 'messenger',
    name: 'Messenger',
    icon: '💬',
    colors: {
      sentBubble: '#0084FF',
      receivedBubble: '#3E4042',
      sentText: '#FFFFFF',
      receivedText: '#E4E6EB',
      background: '#000000',
      header: '#1C1C1E',
      headerText: '#E4E6EB',
      inputBar: '#1C1C1E',
      accent: '#0084FF',
      timestamp: '#B0B3B8',
      statusBar: '#000000',
    },
    features: {
      readReceipts: true,
      typing: true,
      reactions: true,
      replies: true,
      forwarding: true,
      voiceNotes: true,
      onlineStatus: true,
      lastSeen: true,
      editMessage: false,
      deleteMessage: true,
    },
    fonts: {
      primary: "'Helvetica Neue', Helvetica, Arial, sans-serif",
      message: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '18px',
      sentRadius: '18px 18px 4px 18px',
      receivedRadius: '18px 18px 18px 4px',
      maxWidth: '75%',
      padding: '8px 12px',
      hasTail: false,
    },
  },
  twitter: {
    id: 'twitter',
    name: 'X / Twitter DM',
    icon: '𝕏',
    colors: {
      sentBubble: '#1D9BF0',
      receivedBubble: '#2F3336',
      sentText: '#FFFFFF',
      receivedText: '#E7E9EA',
      background: '#000000',
      header: '#000000',
      headerText: '#E7E9EA',
      inputBar: '#16181C',
      accent: '#1D9BF0',
      timestamp: '#71767B',
      statusBar: '#000000',
    },
    features: {
      readReceipts: true,
      typing: false,
      reactions: true,
      replies: true,
      forwarding: false,
      voiceNotes: false,
      onlineStatus: false,
      lastSeen: false,
      editMessage: false,
      deleteMessage: true,
    },
    fonts: {
      primary: "'Chirp', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      message: "'Chirp', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    },
    bubbleStyle: {
      borderRadius: '16px',
      sentRadius: '16px 16px 4px 16px',
      receivedRadius: '16px 16px 16px 4px',
      maxWidth: '75%',
      padding: '10px 14px',
      hasTail: false,
    },
  },
};

export const platformList = Object.values(platformConfigs);
export const getPlatformConfig = (id: string) => platformConfigs[id];
